{{- if .Values.operator -}}
{{- if .Values.operator.enable -}}
{{- if and .Values.operator.rbac.create .Values.operator.watchAnyNamespace -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kaspr-operator
  labels:
    component: role-binding
    {{- include "kaspr.operator.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kaspr.operator.serviceAccountName" . }}
    namespace: {{ include "kaspr.operator.namespace" . }}
roleRef:
  kind: ClusterRole
  name: kaspr-operator
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
{{- end -}}
{{- end -}}
