{{- if .Values.operator -}}
{{- if and .Values.operator.enable .Values.operator.rbac.create (not .Values.operator.watchAnyNamespace) }}
{{- $root := . -}}
{{- $opns := include "kaspr.operator.namespace" . -}}
{{- range append .Values.operator.watchNamespaces $opns }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kaspr-operator-namespaced
  namespace: {{ . }}
  labels:
    component: role-binding
    {{- include "kaspr.operator.labels" $root | nindent 4 }}   
subjects:
  - kind: ServiceAccount
    name: {{ include "kaspr.operator.serviceAccountName" $root }}
    namespace: {{ include "kaspr.operator.namespace" $root }}
roleRef:
  kind: Role
  name: kaspr-operator-namespaced
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
{{- end }}
